# Generated by Django 6.0 on 2025-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
